[2024-05-01T13:55:26.818+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T13:55:26.846+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: try_dag.True manual__2024-05-01T13:55:12.795505+00:00 [queued]>
[2024-05-01T13:55:26.855+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: try_dag.True manual__2024-05-01T13:55:12.795505+00:00 [queued]>
[2024-05-01T13:55:26.856+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T13:55:26.894+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): True> on 2024-05-01 13:55:12.795505+00:00
[2024-05-01T13:55:26.901+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T13:55:26.902+0000] {standard_task_runner.py:63} INFO - Started process 104 to run task
[2024-05-01T13:55:26.902+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'try_dag', 'True', 'manual__2024-05-01T13:55:12.795505+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmpxba8lvsy']
[2024-05-01T13:55:26.904+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask True
[2024-05-01T13:55:26.998+0000] {task_command.py:426} INFO - Running <TaskInstance: try_dag.True manual__2024-05-01T13:55:12.795505+00:00 [running]> on host cab22781d943
[2024-05-01T13:55:27.145+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='try_dag' AIRFLOW_CTX_TASK_ID='True' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:55:12.795505+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:55:12.795505+00:00'
[2024-05-01T13:55:27.147+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T13:55:27.147+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T13:55:27.148+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Success'"]
[2024-05-01T13:55:27.160+0000] {subprocess.py:86} INFO - Output:
[2024-05-01T13:55:27.161+0000] {subprocess.py:93} INFO - Success
[2024-05-01T13:55:27.162+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-01T13:55:27.162+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T13:55:27.234+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=try_dag, task_id=True, execution_date=20240501T135512, start_date=20240501T135526, end_date=20240501T135527
[2024-05-01T13:55:27.317+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T13:55:27.364+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T13:55:27.391+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
