[2024-05-01T13:56:18.390+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T13:56:18.412+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: try_dag.best_performing_model manual__2024-05-01T13:56:11.620050+00:00 [queued]>
[2024-05-01T13:56:18.420+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: try_dag.best_performing_model manual__2024-05-01T13:56:11.620050+00:00 [queued]>
[2024-05-01T13:56:18.421+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T13:56:18.527+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): best_performing_model> on 2024-05-01 13:56:11.620050+00:00
[2024-05-01T13:56:18.550+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T13:56:18.554+0000] {standard_task_runner.py:63} INFO - Started process 122 to run task
[2024-05-01T13:56:18.554+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'try_dag', 'best_performing_model', 'manual__2024-05-01T13:56:11.620050+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmpn_6hwiy0']
[2024-05-01T13:56:18.558+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask best_performing_model
[2024-05-01T13:56:18.682+0000] {task_command.py:426} INFO - Running <TaskInstance: try_dag.best_performing_model manual__2024-05-01T13:56:11.620050+00:00 [running]> on host cab22781d943
[2024-05-01T13:56:18.859+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='try_dag' AIRFLOW_CTX_TASK_ID='best_performing_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:56:11.620050+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:56:11.620050+00:00'
[2024-05-01T13:56:18.861+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T13:56:18.862+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-01T13:56:18.871+0000] {python.py:237} INFO - Done. Returned value was: True
[2024-05-01T13:56:18.872+0000] {branch.py:36} INFO - Branch into True
[2024-05-01T13:56:18.872+0000] {skipmixin.py:178} INFO - Following branch True
[2024-05-01T13:56:18.890+0000] {skipmixin.py:246} INFO - Skipping tasks [('False', -1)]
[2024-05-01T13:56:18.987+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T13:56:19.061+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=try_dag, task_id=best_performing_model, execution_date=20240501T135611, start_date=20240501T135618, end_date=20240501T135619
[2024-05-01T13:56:19.130+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T13:56:19.163+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-01T13:56:19.194+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
