[2024-05-01T13:56:38.097+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T13:56:38.129+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: try_dag.False manual__2024-05-01T13:56:27.213475+00:00 [queued]>
[2024-05-01T13:56:38.140+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: try_dag.False manual__2024-05-01T13:56:27.213475+00:00 [queued]>
[2024-05-01T13:56:38.141+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T13:56:38.178+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): False> on 2024-05-01 13:56:27.213475+00:00
[2024-05-01T13:56:38.189+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T13:56:38.191+0000] {standard_task_runner.py:63} INFO - Started process 145 to run task
[2024-05-01T13:56:38.191+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'try_dag', 'False', 'manual__2024-05-01T13:56:27.213475+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmpbblh0y07']
[2024-05-01T13:56:38.194+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask False
[2024-05-01T13:56:38.278+0000] {task_command.py:426} INFO - Running <TaskInstance: try_dag.False manual__2024-05-01T13:56:27.213475+00:00 [running]> on host cab22781d943
[2024-05-01T13:56:38.463+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='try_dag' AIRFLOW_CTX_TASK_ID='False' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:56:27.213475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:56:27.213475+00:00'
[2024-05-01T13:56:38.465+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T13:56:38.466+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T13:56:38.467+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', " echo 'Failed'"]
[2024-05-01T13:56:38.486+0000] {subprocess.py:86} INFO - Output:
[2024-05-01T13:56:38.490+0000] {subprocess.py:93} INFO - Failed
[2024-05-01T13:56:38.491+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-01T13:56:38.492+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T13:56:38.563+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=try_dag, task_id=False, execution_date=20240501T135627, start_date=20240501T135638, end_date=20240501T135638
[2024-05-01T13:56:38.646+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T13:56:38.669+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T13:56:38.693+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
