[2024-05-01T13:57:24.422+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T13:57:24.446+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: try_dag.True manual__2024-05-01T13:57:12.944303+00:00 [queued]>
[2024-05-01T13:57:24.455+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: try_dag.True manual__2024-05-01T13:57:12.944303+00:00 [queued]>
[2024-05-01T13:57:24.456+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T13:57:24.504+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): True> on 2024-05-01 13:57:12.944303+00:00
[2024-05-01T13:57:24.515+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=163) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T13:57:24.516+0000] {standard_task_runner.py:63} INFO - Started process 165 to run task
[2024-05-01T13:57:24.516+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'try_dag', 'True', 'manual__2024-05-01T13:57:12.944303+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmpivq1c6ya']
[2024-05-01T13:57:24.519+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask True
[2024-05-01T13:57:24.584+0000] {task_command.py:426} INFO - Running <TaskInstance: try_dag.True manual__2024-05-01T13:57:12.944303+00:00 [running]> on host cab22781d943
[2024-05-01T13:57:24.735+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='try_dag' AIRFLOW_CTX_TASK_ID='True' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T13:57:12.944303+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T13:57:12.944303+00:00'
[2024-05-01T13:57:24.738+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T13:57:24.739+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-01T13:57:24.739+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Success'"]
[2024-05-01T13:57:24.753+0000] {subprocess.py:86} INFO - Output:
[2024-05-01T13:57:24.755+0000] {subprocess.py:93} INFO - Success
[2024-05-01T13:57:24.756+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-01T13:57:24.756+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T13:57:24.828+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=try_dag, task_id=True, execution_date=20240501T135712, start_date=20240501T135724, end_date=20240501T135724
[2024-05-01T13:57:24.932+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T13:57:24.978+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T13:57:25.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
